---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  mainfests_path: manifests
  modules_path: modules
  hiera_data_path: hiera
  hiera_config_path: hiera.yaml
  require_chef_for_busser: false

platforms:
  - name: ubuntu-16.04

verifier:
  name: inspec
  sudo: true

suites:
  - name: default
    manifest: site.pp
    verifier:
      inspec_tests:
        - path: test/intergration/default
