---
driver:
  name: ec2
  aws_ssh_key_id: nil
  region: us-west-2

provisioner:
  name: puppet_apply
  mainfests_path: manifests
  modules_path: modules
  hiera_data_path: data
  hiera_config_path: hiera.yaml
  require_chef_for_busser: false

platforms:
  - name: ubuntu-16.04
    driver:
      image_id: ami-96a818fe

suites:
  - name: default
    manifest: site.pp 
