---
driver:
  name: ec2
  aws_ssh_key_id: insecure-test-key-djeche
  region: eu-west-1


transport:
  ssh_key: ~/Downloads/insecure-test-key-djeche.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

provisioner:
  name: puppet_apply
  mainfests_path: manifests
  modules_path: modules
  hiera_data_path: data
  hiera_config_path: hiera.yaml
  require_chef_for_busser: false

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    manifest: site.pp 
